baseURL: https://weilai.media/
languageCode: en-us
title: Wei Lai
paginate: 6
theme: 
  - "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
disablePathToLower: true # making Hugo generate case sensitive urls

minify:
    disableXML: true
    minifyOutput: true

imaging:
  resampleFilter: box
  quality: 75
  hint: photo
  anchor: smart
  exif:
    includeFields: ''
    excludeFields: ''
    disableDate: false
    disableLatLong: true

params:
    mainSections: 
    - projects
    newsSections:
    - news
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Portfolio by Wei Lai
    description: "A collection of Wei Lai's work"
    keywords: [Portfolio, Wei Lai, ]
    author: Me
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: false
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: true
    showtoc: false
    tocopen: false
  
    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi \U0001F64F"
        Content: "My name is [Wei Lai](resume/). I am a [PhD candidate at PolyU Design](https://www.sd.polyu.edu.hk/en/meet-our-students/wei-lai) 
        for designing pedagogical agents with meaningful gestures in virtual learning environments.
        The study used both qualitative and quantitative methods with eye tracking technique and statistical analysis tools.
        My research interest is adopting social science methods with computing tools to investigate human mental and physical needs. 
        In this portfolio, you could find my latest research, design and arts work, a short biography with my [CV](resume/doc/CV-Weilai2020.pdf)." 

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/lai-wei-076310ba/"
        - name: orcid
          url: "https://orcid.org/0000-0002-5476-5450"
        - name: vimeo
          url: "https://vimeo.com/user26095658"
        - name: youtube
          url: "https://www.youtube.com/channel/UCmuyjkQKVcEEOxySic6K0LA"

    cover:
        enableWebP: true # To allow using WebP image src
        responsiveImages: true # To reduce generation time and size of the site
        linkFullImages: true # To enable hyperlinks to the full image size on post pages
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    assets:
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

    # Fusejs
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
        
module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: ยง
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes

menu:
    main:
        - identifier: Projects
          name: projects
          url: /
          weight: 10
        # - identifier: Stories
        #   name: stories
        #   url: /stories/
        #   weight: 20
        - identifier: Resume
          name: resume
          url: /resume/
          weight: 30
        # - identifier: Search
        #   name: search
        #   url: /search/
        #   weight: 40
        - identifier: Tags
          name: tags
          url: /tags/
          weight: 40

outputs:
    home:
        - HTML
        - RSS
        - JSON

markup:
  goldmark:
    extensions:
      footnote: true